name: BioAlloyRAG
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python==3.10.15
  - pip
  # BASICS
  - numpy
  - scipy==1.14.1
  - pandas
  - tqdm==4.67.0
  - click==8.1.7
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of BioAlloyRAG in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - langchain==0.3.7
     - langchain-community==0.3.5
     - langchain-chroma==0.1.4
     - langchain-huggingface==0.1.2
     - pymupdf==1.24.13
     - sentence-transformers==3.2.1
     - faiss-cpu==1.9.0
     - pandas==2.2.3
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
